### ISSUE TITLE
Change RSVP text under header

### ISSUE THREAD

**Issue by hhrucker** [JRileyH/hannahandriley#1]
Can you change the copy under the RSVP header to be below. Feel free to break it up if it feels too blocky: 

"RSVP is for the drinks on evening of June 8th AND the upstate extravaganza from June 9-11th at The Graham & Co in Phoenicia. For The Graham & Co, we already have the rooms booked and payed for, but will give them your info so you can check-in! If you need any help with travel upstate please let us know. Please reach out to Hannah with any questions (610-703-3554)."

**Comment by JRileyH** [comment]
https://github.com/JRileyH/hannahandriley/commit/8b753c0cfd62e534ff4b011dc95b1f04868042f0
Done.
