### ISSUE TITLE
Nav Bar on RSVP Page is incorrect

### ISSUE THREAD

**Issue by hhrucker** [JRileyH/hannahandriley#2]
I think this was an issue when I did it in webflow, but when you're on the RSVP page, the nav bar has "for friends" and "for family" instead of "itinerary" and "stuff to do" on the nav bar at the top. 
<img width="1228" alt="Screen Shot 2022-09-14 at 10 54 24 PM" src="https://user-images.githubusercontent.com/20031161/190303051-07fbf49a-e2e8-4575-9cb6-56e578bf4f06.png">

**Comment by JRileyH** [comment]
Fixed with: https://github.com/JRileyH/hannahandriley/commit/a09a38bab1f54478d35c4bf7a7ec6070e0e3e596
