### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by hhrucker** [JRileyH/hannahandriley#3]
When links are clicked on, can they open in a new tab instead of just going straight there on the page? Thanks!!

**Comment by JRileyH** [comment]
Yes but which links are we referring to? The way you could do this is add `target="_blank"` to your `<a>` tags.
For example:
```<a href="https://website.com">Link Text!</a>```
becomes
```<a href="https://website.com" target="_blank">Link Text!</a>```

And the second link would open a new tab and change focus to it

**Comment by hhrucker** [comment]
Oh oops sorry, text hyperlinks, I can change those in the text!
